In [112]:
import numpy as np
a= np.arange(0, 350, 40,dtype=np.uint16)

In [113]:
a

array([  0,  40,  80, 120, 160, 200, 240, 280, 320], dtype=uint16)

In [114]:
a.nbytes

18

In [115]:
from skimage.util import img_as_bool, img_as_uint, img_as_ubyte
from skimage.io import imread

In [116]:
b = img_as_ubyte(a)

C:\Users\jesse\Anaconda3\lib\site-packages\skimage\util\dtype.py:122: UserWarning: Possible precision loss when converting from uint16 to uint8
  .format(dtypeobj_in, dtypeobj_out))


In [117]:
b.nbytes

9

In [118]:
b

array([0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=uint8)

In [119]:
from cv2 import convertScaleAbs

In [124]:
a.max()

320

In [129]:
### This is how we scale properly

d = (a * (255/a.max())).astype(np.uint8)

In [130]:
print(d)

[  0  31  63  95 127 159 191 223 255]


In [136]:
np.array([[0,1,255]]).astype(np.uint8)

array([[  0,   1, 255]], dtype=uint8)